<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSv7n4QP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSv7n4QP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSv7n4QP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSv7n4QP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSv7n4QP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sv7n4QP',
    'container.build_id' => 'fc89c7cf',
    'container.build_time' => 1648147791,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSv7n4QP');
